name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ACTIONS_KEY }}

    # - name: Execute SSH commands
    #   run: |
    #    ssh -o StrictHostKeyChecking=no root@138.68.71.251 '
    #     cd /srv/quitnut-backend && 
    #     git config user.email "novatovvv@gmail.com" &&
    #     git config user.name "Andrei" &&
    #     git config pull.rebase true &&
    #     git add .
    #     if [ -z "$(git status --porcelain)" ]; then
    #       echo "No changes to commit";
    #     else
    #       git commit -m "[skip ci] Update configurations" &&
    #       git push;
    #     fi' && git fetch --all && git reset --hard origin/main && git pull
      